# Programa para sacar costo del Panettone
h = float(input("Costo de la Harina por Kg: "))
hq = float(input("Cantidad Requerida de Harina en Kg: "))
m = float(input("Costo de la Mantequilla por Kg: "))
mq = float(input("Cantidad Requerida de Mantequilla en Kg: "))
a = float(input("Costo del Azucar por Kg: "))
aq = float(input("Cantidad Requerida de Azucar en Kg: "))
v = float(input("Costo de la Mantequilla por Unidad: "))
vq = float(input("Cantidad Requerida de Huevo por Unidad: "))
r = float(input("Costo del Relleno por Kg: "))
rq = float(input("Cantidad Requerida del Relleno en Kg: "))
l = float(input("Costo de la Levadura por Kg: "))
lq = float(input("Cantidad Requerida de Levadura en Kg: "))
le = float(input("Costo de la leche por Litro: "))
leq = float(input("Cantidad Requerida por Litro: "))
w = float(input("Costo del agua potable por litro: "))
wq = float(input("Cantidad Requerida de agua potable por litro: "))
mi = float(input("Costo de la Miel por Kg: "))
miq = float(input("Cantidad Requerida de Miel por Kg: "))
s = float(input("Costo de la Sal por Kg: "))
sq = float(input("Cantidad Requerida de Sal por Kg: "))
n = float(input("Costo de la Naranja por Kg: "))
nq = float(input("Cantidad Requerida de Naranja por Kg: "))
e = float(input("Costo de Energia en Kw: "))
eq = float(input("Cantidad Requerida de Energia en Kw/h: "))
d = float(input("Costo de la Depreciacion del Horno en 12 meses: "))
dq = float(input("Cantidad Requerida en tiempo mes: "))

# Formula
Panettone = (h*hq)+(m*mq)+(a*aq)+(v*vq)+(r*rq)+(l*lq)+(le*leq)+(w*wq)+(mi*miq)+(s*sq)+(n*nq)+(e*eq)+(d*dq)
print("Costo por Panetton: ", Panettone)
